# Generated by Django 3.1.6 on 2021-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0005_message_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dm',
            field=models.BooleanField(default=False),
        ),
    ]
