# Generated by Django 3.1.6 on 2021-02-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0006_message_dm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
