# Generated by Django 3.1.6 on 2021-02-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0008_auto_20210213_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
