# Generated by Django 3.1.6 on 2021-02-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0010_auto_20210214_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='amount',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
    ]
